baseURL = 'https://vida-nyu.github.io/DISN-Wildlife/'
languageCode = 'en-us'
title = 'DISN Wildlife Research Project'

theme = 'astatine'

preserveTaxonomyNames = true
rssLimit = 10
paginate = 10

# Code highlighting
pygmentsCodefences = true
pygmentsStyle = "native"

# Taxonomies (only tags and categories are supported out of the box but you can
# add more)
[taxonomies]
    news = "news"  
    team = "team"

# Configure permalinks style
[permalinks]
    post = "/:slug/"
    page = "/:slug/"

# This links to the page about.md
[[menu.main]]
    name = "The project"
    url = "#project"
    weight = 1

# Make the tags and categories pages accessible directly from the navbar.
[[menu.main]]
    name = "Team"
    url = "#team"
    weight = 2

# Make the tags and categories pages accessible directly from the navbar.
[[menu.main]]
    name = "News"
    url = "#news"
    weight = 3

# Site wide params and SEO
[params]
    # Site description. Individual pages can have descriptions too but if
    # missing it will fallback to that one.
    description = """DISN wildlife webpage"""
    # Author of the site
    authorName = "Juliana Barbosa"
    # Main image for the author. This will be the default image for SEO.




# Sitemap location (default is /sitemap.xml)
[sitemap]
  filename = "sitemap.xml"